version: 2

workflows:
  version: 2
  workflow:
    jobs:
      - lint
      - test-3.10
      - test-3.11
      - test-3.12
      - test-3.13

defaults: &defaults
  working_directory: ~/code
  steps:
  - checkout
  - run:
      name: Install dependencies
      command: pip install --user -r requirements.txt
  - run:
      name: Test
      command: |
        export PATH=$HOME/.local/bin:$PATH
        pytest

jobs:
  lint:
    working_directory: ~/code
    docker:
    - image: python:3.13
    steps:
    - checkout
    - run:
        name: Install dependencies
        command: pip install --user -r requirements.txt
    - run:
        name: Format
        command: |
          export PATH=$HOME/.local/bin:$PATH
          ruff format --check --no-cache
    - run:
        name: Lint
        command: |
          export PATH=$HOME/.local/bin:$PATH
          ruff check --no-cache
  test-3.10:
    <<: *defaults
    docker:
    - image: python:3.10
    - image: redis:7.2.4
  test-3.11:
    <<: *defaults
    docker:
    - image: python:3.11
    - image: redis:7.2.4
  test-3.12:
    <<: *defaults
    docker:
    - image: python:3.12
    - image: redis:7.2.4
  test-3.13:
    <<: *defaults
    docker:
    - image: python:3.13
    - image: redis:7.2.4
