version: 2

workflows:
  version: 2
  workflow:
    jobs:
      - lint
      - test-3.8
      - test-3.9
      - test-3.10
      - test-3.11
      - test-3.12

defaults: &defaults
  working_directory: ~/code
  steps:
  - checkout
  - run:
      name: Install dependencies
      command: pip install --user -r requirements.txt
  - run:
      name: Test
      command: |
        export PATH=$HOME/.local/bin:$PATH
        pytest tests.py

jobs:
  lint:
    working_directory: ~/code
    docker:
    - image: python:3.12
    steps:
    - checkout
    - run:
        name: Install dependencies
        command: pip install --user -r requirements.txt
    - run:
        name: ruff
        command: |
          export PATH=$HOME/.local/bin:$PATH
          ruff check --no-cache .
    - run:
        name: Black
        command: |
          export PATH=$HOME/.local/bin:$PATH
          black --check .
    - run:
        name: isort
        command: |
          export PATH=$HOME/.local/bin:$PATH
          isort --check .
  test-3.8:
    <<: *defaults
    docker:
    - image: python:3.8
    - image: redis:7.2.4
  test-3.9:
    <<: *defaults
    docker:
    - image: python:3.9
    - image: redis:7.2.4
  test-3.10:
    <<: *defaults
    docker:
    - image: python:3.10
    - image: redis:7.2.4
  test-3.11:
    <<: *defaults
    docker:
    - image: python:3.11
    - image: redis:7.2.4
  test-3.12:
    <<: *defaults
    docker:
    - image: python:3.12
    - image: redis:7.2.4
